name: deploy

on:
  push:
    branches:
      - main  # Change to the default branch name in your repository
  workflow_dispatch:

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy to Vercel
        run: |
          vercel pull --yes --environment=production --token=${VERCEL_TOKEN}
          vercel build --prod --token=${VERCEL_TOKEN}
          vercel deploy --prod --prebuilt --token=${VERCEL_TOKEN}
